import Head from "next/head";

import { Navbar } from "@components/Navbar";
import { Footer } from "@components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>yae-food</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <Footer />
    </>
  );
}
