import { FaInstagram, FaWhatsapp } from "react-icons/fa";

import ChefSVG from "@assets/chef.svg";
import DeliverySVG from "@assets/delivery.svg";
import OrderSVG from "@assets/order.svg";
import QuestionSVG from "@assets/question.svg";
import { Footer } from "@components/Footer";
import { Navbar } from "@components/Navbar";
import {
  Container,
  Welcome,
  Section,
  Content,
  Button,
  Social,
  GroupLinks,
} from "@styles/Home";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>yae-food</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Navbar />

      <Container>
        <Welcome>
          <Content>
            <h1>Bem vindo ao nosso negócio!</h1>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit ut
              aliquam, purus sit amet luctus venenatis, cumids e meis
            </p>
          </Content>

          <Image
            src={ChefSVG}
            alt="Bem vindo ao yae-food!"
            width={463}
            height={360}
          />
        </Welcome>

        <Section>
          <Image
            src={DeliverySVG}
            alt="Entrega em domicílio"
            width={506}
            height={223}
          />

          <Content>
            <h1>Nossa entrega</h1>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit ut
              aliquam, purus sit amet luctus venenatis, lectus magna fringilla
              urna, porttitor rhoncus dolor purus non enim praesent elementum
              facilisis leo.
            </p>

            <Link href="/locais" passHref>
              <Button>Locais de entrega</Button>
            </Link>
          </Content>
        </Section>

        <Section>
          <Content>
            <h1>Monte seu pedido</h1>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit ut
              aliquam, purus sit amet luctus venenatis, lectus magna fringilla
              urna, porttitor rhoncus dolor purus non enim praesent elementum
              facilisis leo.
            </p>

            <Link href="/pedido" passHref>
              <Button>Fazer pedido</Button>
            </Link>
          </Content>

          <Image
            src={OrderSVG}
            alt="Faça seu pedido!"
            width={457}
            height={432}
          />
        </Section>

        <Section>
          <Image
            src={QuestionSVG}
            alt="Dúvidas fale conosco!"
            width={526}
            height={371}
          />

          <Content>
            <h1>Alguma dúvida ou sugestão?</h1>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit ut
              aliquam, purus sit amet luctus venenatis, lectus magna fringilla
              urna, porttitor rhoncus dolor purus non enim praesent elementum
              facilisis leo.
            </p>

            <GroupLinks>
              <Link href="/pedido" passHref>
                <Button>Escrever email</Button>
              </Link>

              <Social href="#">
                <FaInstagram />
              </Social>

              <Social href="#">
                <FaWhatsapp />
              </Social>
            </GroupLinks>
          </Content>
        </Section>
      </Container>

      <Footer />
    </>
  );
}
