import Head from "next/head";

export default function Home() {
  return (
    <main>
      <Head>
        <title>yae-food</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </main>
  );
}
